In [36]:
# 이미지 띄우기
import cv2

img = cv2.imread('images/kitten.jpg')

cv2.imshow('cat', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[]


In [47]:
img = cv2.imread('images/cat9.jpg')
result = model(img)
detect = result.xyxyn[0].numpy() # 찾은 객체 관련 값
detect

array([[   0.040001,     0.18257,      0.2975,     0.45898,      0.9087,           0],
       [    0.38373,    0.073844,     0.63468,     0.36971,     0.90098,           0],
       [    0.66157,     0.12129,     0.94607,     0.39914,     0.86272,           0]], dtype=float32)

In [4]:
# 객체 검출해보기
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path = 'best.pt', force_reload = True)

Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\gjaischool1/.cache\torch\hub\master.zip
YOLOv5  2023-10-26 Python-3.8.18 torch-2.1.0+cpu CPU

Fusing layers... 
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


In [5]:
img

array([[[ 49,  62, 108],
        [ 49,  62, 108],
        [ 49,  62, 108],
        ...,
        [116,  84,  73],
        [116,  84,  73],
        [116,  84,  73]],

       [[ 49,  62, 108],
        [ 49,  62, 108],
        [ 49,  62, 108],
        ...,
        [114,  82,  71],
        [114,  82,  71],
        [114,  82,  71]],

       [[ 49,  62, 108],
        [ 49,  62, 108],
        [ 48,  61, 107],
        ...,
        [113,  81,  70],
        [113,  81,  70],
        [113,  81,  70]],

       ...,

       [[ 48,  34,  36],
        [ 48,  34,  36],
        [ 48,  34,  36],
        ...,
        [ 59,  45,  47],
        [ 60,  46,  48],
        [ 61,  47,  49]],

       [[ 48,  34,  36],
        [ 48,  34,  36],
        [ 48,  34,  36],
        ...,
        [ 58,  44,  46],
        [ 59,  45,  47],
        [ 60,  46,  48]],

       [[ 48,  34,  36],
        [ 48,  34,  36],
        [ 48,  34,  36],
        ...,
        [ 57,  43,  45],
        [ 58,  44,  46],
        [ 59,  45,  47]]

In [50]:
import numpy
img = cv2.imread('images/cat9.jpg')
result = model(img)
detect = result.xyxyn[0].numpy() # 찾은 객체 관련 값
# x1, y1, x2, y2, confidence, class

# 객체 실제 위치 계산하기
y_shape = img.shape[0]
x_shape = img.shape[1]

for i in range(len(detect)):
    x1 = int(detect[i, 0] * x_shape)
    y1 = int(detect[i, 1] * y_shape)
    x2 = int(detect[i, 2] * x_shape)
    y2 = int(detect[i, 3] * y_shape)
    
    # 객체 위치에 표현하기
    # 이미지, 좌상단 좌표, 우하단 좌표, 색상(BGR), 두께 
    cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)

cv2.imshow('cat', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
detect

array([[   0.077661,    0.027088,     0.88498,     0.81115,     0.60782,           0]], dtype=float32)

In [28]:
y_shape = img.shape[0]
x_shape = img.shape[1]

x1 = int(detect[0, 0] * x_shape)
y1 = int(detect[0, 1] * y_shape)
x2 = int(detect[0, 2] * x_shape)
y2 = int(detect[0, 3] * y_shape)

In [22]:
y2

0.8111502

In [29]:
x1

24

In [24]:
img.shape # y, x값

In [63]:
import cv2

cap = cv2.VideoCapture("images/sesame.mp4")

while cap.isOpened() :

    ret, frame = cap.read() # 초당 30번은 실행시켜야함

    result = model(frame)
    detect = result.xyxyn[0].numpy() # 찾은 객체 관련 값
    # x1, y1, x2, y2, confidence, class
    
    # 객체 실제 위치 계산하기
    y_shape = frame.shape[0]
    x_shape = frame.shape[1]
    
    for i in range(len(detect)):
        x1 = int(detect[i, 0] * x_shape)
        y1 = int(detect[i, 1] * y_shape)
        x2 = int(detect[i, 2] * x_shape)
        y2 = int(detect[i, 3] * y_shape)
    
    # 객체 위치에 표현하기
    # 이미지, 좌상단 좌표, 우하단 좌표, 색상(BGR), 두께 
    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
    
    if not ret :
        print("종료")
        break
        
    cv2.imshow("video", frame)
    
    key = cv2.waitKey(1) # 객체 탐지하는데 시간이 걸리기 때문에 여기서 딜레이를 줄 필요는 없음

    if key == 49 :
        print("종료")
        break
        
cap.release()
cv2.destroyAllWindows()

종료
